import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        // Nav
        dashboard: "Dashboard",
        fileComplaint: "File Complaint",
        policyAssistant: "Policy Assistant",
        docVerification: "Document Verification",
        analytics: "Analytics Overview",
        admin: "Admin Console",
        // Header
        welcome: "Welcome back,",
        citizen: "Citizen",
        accessibility: "Accessibility",
        // Dashboard
        totalComplaints: "Total Complaints",
        resolved: "Resolved",
        pending: "Pending",
        inProgress: "In Progress",
        recentComplaints: "Recent Complaints",
        viewAll: "View All",
        heroTitle: "Welcome to CivicNexus AI",
        heroDesc: "Your one-stop platform for civic engagement. File complaints, get policy assistance, verify documents, and track progress—all powered by advanced AI technology.",
        heroBtnComplaint: "File New Complaint",
        heroBtnPolicy: "Ask Policy Question",
        // Complaint
        beDetailed: "Please describe the issue in detail...",
        describeComplaint: "Describe your complaint *",
        location: "Location *",
        enterLocation: "Enter the address or landmark",
        department: "Department *",
        selectDept: "Select Department",
        category: "Category *",
        selectCat: "Select category",
        urgency: "Urgency Level",
        low: "Low",
        medium: "Medium",
        high: "High",
        attachEvidence: "Attach Evidence (Optional)",
        dragDrop: "Drag & drop files here, or click to browse",
        submitComplaint: "Submit Complaint",
        complaintTitle: "File a Complaint",
        complaintSubtitle: "Report civic issues and track their resolution",
        // Policy
        policyTitle: "Policy Assistant",
        policySubtitle: "Get answers about government policies and schemes",
        searchPlaceholder: "Search policies and schemes...",
        catLand: "Land & Property",
        catServices: "Citizen Services",
        catWelfare: "Welfare Schemes",
        landRecords: "Land Records & Registration",
        propTax: "Property Tax Regulations",
        domicile: "Domicile & Income Certificates",
        marriageReg: "Marriage Registration",
        pmKisan: "PM-KISAN Scheme",
        ayushman: "Ayushman Bharat",
        usefulPortals: "Useful Government Portals",
        // Document
        docTitle: "Document Verification",
        docSubtitle: "Verify the authenticity of government documents",
        uploadDocs: "Upload Documents",
        browseFiles: "Browse Files",
        supportedDocs: "Supported Document Types",
        noDocs: "No documents uploaded yet",
        // Analytics
        analyticsTitle: "Analytics Overview",
        analyticsSubtitle: "Track complaint trends and department performance",
        resRate: "Resolution Rate",
        avgTime: "Avg. Resolution Time",
        byDept: "Complaints by Department",
        monthlyTrend: "Monthly Trend",
        // Chat
        aiAssistant: "AI Assistant",
        online: "Online",
        typeMessage: "Type your message...",
        generating: "Generating response...",
        complaintContext: "Hello! I'm here to help you file your complaint. You can describe your issue in the form, or tell me about it here and I'll help guide you through the process.",
        policyContext: "Hello! I'm your Policy Assistant. Ask me anything about government schemes. I can help you understand eligibility and application processes.",
        genContext: "Hello! I am your AI Assistant. How can I help you today?",
        // Admin
        adminTitle: "Admin Console",
        adminSubtitle: "Overview of civic issues and department performance",
        downloadReports: "Download Reports",
        totalCitizens: "Total Citizens",
        openComplaints: "Open Complaints",
        resolvedMonth: "Resolved This Month",
        pendingVerif: "Pending Verifications",
        recentIssues: "Recent High Priority Issues",
        id: "Complaint ID",
        issue: "Issue",
        status: "Status",
        action: "Action",
        view: "View"
    },
    hi: {
        // Nav
        dashboard: "डैशबोर्ड",
        fileComplaint: "शिकायत दर्ज करें",
        policyAssistant: "नीति सहायक",
        docVerification: "दस्तावेज़ सत्यापन",
        analytics: "विश्लेषण अवलोकन",
        admin: "प्रशासन कंसोल",
        // Header
        welcome: "वापसी पर स्वागत है,",
        citizen: "नागरिक",
        accessibility: "सुगमता",
        // Dashboard
        totalComplaints: "कुल शिकायतें",
        resolved: "समाधान",
        pending: "लंबित",
        inProgress: "प्रक्रिया में",
        recentComplaints: "हाल की शिकायतें",
        viewAll: "सभी देखें",
        heroTitle: "सिविकनेक्सस एआई में आपका स्वागत है",
        heroDesc: "नागरिक जुड़ाव के लिए आपका वन-स्टॉप प्लेटफॉर्म। शिकायत दर्ज करें, नीति सहायता प्राप्त करें, दस्तावेजों का सत्यापन करें और प्रगति को ट्रैक करें - यह सब उन्नत एआई तकनीक द्वारा संचालित है।",
        heroBtnComplaint: "नई शिकायत दर्ज करें",
        heroBtnPolicy: "नीति प्रश्न पूछें",
        // Complaint
        beDetailed: "कृपया विस्तार से समस्या का वर्णन करें...",
        describeComplaint: "अपनी शिकायत का वर्णन करें *",
        location: "स्थान *",
        enterLocation: "पता या लैंडमार्क दर्ज करें",
        department: "विभाग *",
        selectDept: "विभाग चुनें",
        category: "श्रेणी *",
        selectCat: "श्रेणी चुनें",
        urgency: "तात्कालिकता स्तर",
        low: "कम",
        medium: "मध्यम",
        high: "उच्च",
        attachEvidence: "प्रमाण संलग्न करें (वैकल्पिक)",
        dragDrop: "फाइलें यहाँ खींचें, या ब्राउज़ करने के लिए क्लिक करें",
        submitComplaint: "शिकायत जमा करें",
        complaintTitle: "शिकायत दर्ज करें",
        complaintSubtitle: "नागरिक समस्याओं की रिपोर्ट करें और उनके समाधान को ट्रैक करें",
        // Policy
        policyTitle: "नीति सहायक",
        policySubtitle: "सरकारी नीतियों और योजनाओं के बारे में उत्तर प्राप्त करें",
        searchPlaceholder: "नीतियां और योजनाएं खोजें...",
        catLand: "भूमि और संपत्ति",
        catServices: "नागरिक सेवाएं",
        catWelfare: "कल्याणकारी योजनाएं",
        landRecords: "भूमि रिकॉर्ड और पंजीकरण",
        propTax: "संपत्ति कर नियम",
        domicile: "अधिवास और आय प्रमाण पत्र",
        marriageReg: "विवाह पंजीकरण",
        pmKisan: "पीएम-किसान योजना",
        ayushman: "आयुष्मान भारत",
        usefulPortals: "उपयोगी सरकारी पोर्टल",
        // Document
        docTitle: "दस्तावेज़ सत्यापन",
        docSubtitle: "सरकारी दस्तावेजों की प्रमाणिकता सत्यापित करें",
        uploadDocs: "दस्तावेज़ अपलोड करें",
        browseFiles: "फाइलें ब्राउज़ करें",
        supportedDocs: "समर्थित दस्तावेज़ प्रकार",
        noDocs: "अभी तक कोई दस्तावेज़ अपलोड नहीं किया गया",
        // Analytics
        analyticsTitle: "विश्लेषण अवलोकन",
        analyticsSubtitle: "शिकायत के रुझान और विभाग के प्रदर्शन को ट्रैक करें",
        resRate: "समाधान दर",
        avgTime: "औसत समाधान समय",
        byDept: "विभाग द्वारा शिकायतें",
        monthlyTrend: "मासिक रुझान",
        // Chat
        aiAssistant: "एआई सहायक",
        online: "ऑनलाइन",
        typeMessage: "अपना संदेश लिखें...",
        generating: "प्रतिक्रिया उत्पन्न हो रही है...",
        complaintContext: "नमस्ते! मैं आपकी शिकायत दर्ज करने में मदद करने के लिए यहाँ हूँ। आप फॉर्म में अपनी समस्या का वर्णन कर सकते हैं, या मुझे यहाँ बता सकते हैं।",
        policyContext: "नमस्ते! मैं आपका नीति सहायक हूँ। सरकारी योजनाओं, प्रक्रियाओं या नियमों के बारे में मुझसे कुछ भी पूछें।",
        genContext: "नमस्ते! मैं आपका सिविकनेक्सस सहायक हूँ। आज मैं आपकी कैसे मदद कर सकता हूँ?",
        // Admin
        adminTitle: "प्रशासन कंसोल",
        adminSubtitle: "नागरिक मुद्दों और विभाग के प्रदर्शन का अवलोकन",
        downloadReports: "रिपोर्ट डाउनलोड करें",
        totalCitizens: "कुल नागरिक",
        openComplaints: "खुली शिकायतें",
        resolvedMonth: "इस महीने हल",
        pendingVerif: "लंबित सत्यापन",
        recentIssues: "हालिया उच्च प्राथमिकता वाले मुद्दे",
        id: "शिकायत आईडी",
        issue: "मुद्दा",
        status: "स्थिति",
        action: "कार्रवाई",
        view: "देखें"
    },
    ta: {
        // Nav
        dashboard: "டாஷ்போர்டு",
        fileComplaint: "புகார் அளிக்கவும்",
        policyAssistant: "காள்கை உதவியாளர்",
        docVerification: "ஆவண சரிபார்ப்பு",
        analytics: "பகுப்பாய்வு",
        admin: "நிர்வாகம்",
        // Header
        welcome: "மீண்டும் வருக,",
        citizen: "குடிமகன்",
        accessibility: "அணுகல்",
        // Dashboard
        totalComplaints: "மொத்த புகார்கள்",
        resolved: "தீர்க்கப்பட்டது",
        pending: "நிலுவையில்",
        inProgress: "செயல்பாட்டில்",
        recentComplaints: "சமீபத்திய புகார்கள்",
        viewAll: "அனைத்தையும் காண்க",
        heroTitle: "CivicNexus AIக்கு வரவேற்கிறோம்",
        heroDesc: "குடிமக்கள் ஈடுபாட்டிற்காக உங்கள் தளம். புகார்களை பதிவு செய்யவும், கொள்கை உதவியைப் பெறவும், ஆவணங்களைச் சரிபார்க்கவும்.",
        heroBtnComplaint: "புதிய புகார்",
        heroBtnPolicy: "கொள்கை கேள்வி",
        // Complaint
        beDetailed: "தயவுசெய்து சிக்கலை விரிவாக விவரிக்கவும்...",
        describeComplaint: "புகாரை விவரிக்கவும் *",
        location: "இடம் *",
        enterLocation: "முகவரி அல்லது அடையாளத்தை உள்ளிடவும்",
        department: "துறை *",
        selectDept: "துறையைத் தேர்ந்தெடுக்கவும்",
        category: "வகை *",
        selectCat: "வகையைத் தேர்ந்தெடுக்கவும்",
        urgency: "அவசர நிலை",
        low: "குறைந்த",
        medium: "நடுத்தர",
        high: "உயர்",
        attachEvidence: "சான்றுகளை இணைக்கவும் (விருப்பத் தேர்வு)",
        dragDrop: "கோப்புகளை இங்கே இழுக்கவும்",
        submitComplaint: "புகாரைச் சமர்ப்பிக்கவும்",
        complaintTitle: "புகார் அளிக்கவும்",
        complaintSubtitle: "குடிமைப் பிரச்சனைகளைப் புகாரளித்து தீர்வுகளைக் கண்காணிக்கவும்",
        // Policy
        policyTitle: "கொள்கை உதவியாளர்",
        policySubtitle: "அரசுத் திட்டங்கள் பற்றிய பதில்களைப் பெறுங்கள்",
        searchPlaceholder: "திட்டங்களைத் தேடுங்கள்...",
        catLand: "நிலம் & சொத்து",
        catServices: "குடிமக்கள் சேவைகள்",
        catWelfare: "நலத் திட்டங்கள்",
        landRecords: "நில ஆவணங்கள் பதிவு",
        propTax: "சொத்து வரி விதிகள்",
        domicile: "குடியிருப்பு சான்றிதழ்",
        marriageReg: "திருமண பதிவு",
        pmKisan: "பிஎம்-கிசான் திட்டம்",
        ayushman: "ஆயுஷ்மான் பாரத்",
        usefulPortals: "பயனுள்ள இணையதளங்கள்",
        // Document
        docTitle: "ஆவண சரிபார்ப்பு",
        docSubtitle: "அரசு ஆவணங்களின் நம்பகத்தன்மையைச் சரிபார்க்கவும்",
        uploadDocs: "ஆவணங்களைப் பதிவேற்றவும்",
        browseFiles: "கோப்புகளை உலாவவும்",
        supportedDocs: "ஆதரிக்கப்படும் ஆவணங்கள்",
        noDocs: "ஆவணங்கள் எதுவும் பதிவேற்றப்படவில்லை",
        // Analytics
        analyticsTitle: "பகுப்பாய்வு",
        analyticsSubtitle: "புகார் போக்குகளைக் கண்காணிக்கவும்",
        resRate: "தீர்வு விகிதம்",
        avgTime: "சராசரி தீர்வு நேரம்",
        byDept: "துறை வாரியாக",
        monthlyTrend: "மாதாந்திர போக்கு",
        // Chat
        aiAssistant: "AI உதவியாளர்",
        online: "ஆன்லைன்",
        typeMessage: "செய்தியை உள்ளிடவும்...",
        generating: "பதில் தயாராகிறது...",
        complaintContext: "வணக்கம்! புகார் அளிக்க நான் உதவுகிறேன்.",
        policyContext: "வணக்கம்! நான் உங்கள் கொள்கை உதவியாளர்.",
        genContext: "வணக்கம்! நான் உங்கள் CivicNexus உதவியாளர்.",
        // Admin
        adminTitle: "நிர்வாக கன்சோல்",
        adminSubtitle: "குடிமை சிக்கல்கள் ஒரு பார்வை",
        downloadReports: "அறிக்கைகளைப் பதிவிறக்கவும்",
        totalCitizens: "மொத்த குடிமக்கள்",
        openComplaints: "திறந்த புகார்கள்",
        resolvedMonth: "இந்த மாதம் தீர்க்கப்பட்டது",
        pendingVerif: "நிலுவையில் உள்ள சரிபார்ப்புகள்",
        recentIssues: "சமீபத்திய உயர் முன்னுரிமை சிக்கல்கள்",
        id: "புகார் எண்",
        issue: "சிக்கல்",
        status: "நிலை",
        action: "செயல்",
        view: "பார்வை"
    },
    mr: {
        // Nav
        dashboard: "डॅशबोर्ड",
        fileComplaint: "तक्रार दाखल करा",
        policyAssistant: "धोरण सहाय्यक",
        docVerification: "कागदपत्र पडताळणी",
        analytics: "विश्लेषण",
        admin: "प्रशासन",
        // Header
        welcome: "परत स्वागत आहे,",
        citizen: "नागरिक",
        accessibility: "सुलभता",
        // Dashboard
        totalComplaints: "एकूण तक्रारी",
        resolved: "सोडवले",
        pending: "प्रलंबित",
        inProgress: "प्रगतीपथावर",
        recentComplaints: "अलीकडील तक्रारी",
        viewAll: "सर्व पहा",
        heroTitle: "CivicNexus AI मध्ये आपले स्वागत आहे",
        heroDesc: "नागरिक सहभागासाठी आपले वन-स्टॉप प्लॅटफॉर्म. तक्रारी दाखल करा, मदत मिळवा आणि प्रगतीचा मागोवा घ्या.",
        heroBtnComplaint: "नवीन तक्रार दाखल करा",
        heroBtnPolicy: "धोरण प्रश्न विचारा",
        // Complaint
        beDetailed: "कृपया समस्येचे तपशीलवार वर्णन करा...",
        describeComplaint: "आपल्या तक्रारीचे वर्णन करा *",
        location: "स्थान *",
        enterLocation: "पत्ता किंवा लँडमार्क प्रविष्ट करा",
        department: "विभाग *",
        selectDept: "विभाग निवडा",
        category: "श्रेणी *",
        selectCat: "श्रेणी निवडा",
        urgency: "निकड पातळी",
        low: "कमी",
        medium: "मध्यम",
        high: "उच्च",
        attachEvidence: "पुरावा जोडा (पर्यायी)",
        dragDrop: "फाइल्स येथे ड्रॉप करा",
        submitComplaint: "तक्रार सबमिट करा",
        complaintTitle: "तक्रार दाखल करा",
        complaintSubtitle: "नागरिक समस्यांची तक्रार करा आणि ट्रॅक करा",
        // Policy
        policyTitle: "धोरण सहाय्यक",
        policySubtitle: "सरकारी योजनांबद्दल उत्तरे मिळवा",
        searchPlaceholder: "योजना शोधा...",
        catLand: "जमीन आणि मालमत्ता",
        catServices: "नागरिक सेवा",
        catWelfare: "कल्याणकारी योजना",
        landRecords: "जमीन रेकॉर्ड आणि नोंदणी",
        propTax: "मालमत्ता कर नियम",
        domicile: "अधिवास प्रमाणपत्र",
        marriageReg: "विवाह नोंदणी",
        pmKisan: "पीएम-किसान योजना",
        ayushman: "आयुष्यमान भारत",
        usefulPortals: "उपयुक्त सरकारी पोर्टल्स",
        // Document
        docTitle: "कागदपत्र पडताळणी",
        docSubtitle: "सरकारी कागदपत्रांची पडताळणी करा",
        uploadDocs: "कागदपत्रे अपलोड करा",
        browseFiles: "फाइल्स ब्राउझ करा",
        supportedDocs: "समर्थित कागदपत्र प्रकार",
        noDocs: "अद्याप कोणतीही कागदपत्रे अपलोड केलेली नाहीत",
        // Analytics
        analyticsTitle: "विश्लेषण विहंगावलोकन",
        analyticsSubtitle: "तक्रार ट्रेंड आणि विभागाच्या कामगिरीचा मागोवा घ्या",
        resRate: "निराकरण दर",
        avgTime: "सरासरी निराकरण वेळ",
        byDept: "विभागानुसार तक्रारी",
        monthlyTrend: "मासिक कल",
        // Chat
        aiAssistant: "AI सहाय्यक",
        online: "ऑनलाइन",
        typeMessage: "आपला संदेश टाइप करा...",
        generating: "प्रतिसाद तयार होत आहे...",
        complaintContext: "नमस्कार! मी तुम्हाला तक्रार दाखल करण्यात मदत करण्यासाठी येथे आहे.",
        policyContext: "नमस्कार! मी तुमचा धोरण सहाय्यक आहे. सरकारी योजनांबद्दल मला काहीही विचारा.",
        genContext: "नमस्कार! मी तुमचा CivicNexus सहाय्यक आहे. मी तुम्हाला कशी मदत करू शकतो?",
        // Admin
        adminTitle: "प्रशासन कन्सोल",
        adminSubtitle: "नागरिक समस्या आणि विभाग कामगिरीचे विहंगावलोकन",
        downloadReports: "अहवाल डाउनलोड करा",
        totalCitizens: "एकूण नागरिक",
        openComplaints: "खुली तक्रारी",
        resolvedMonth: "या महिन्यात सोडवले",
        pendingVerif: "प्रलंबित पडताळणी",
        recentIssues: "अलीकडील उच्च प्राधान्य समस्या",
        id: "तक्रार आयडी",
        issue: "समस्या",
        status: "स्थिती",
        action: "कृती",
        view: "पहा"
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('hi'); // Defaulting to Hindi as requested

    const t = (key) => {
        if (key === 'langCode') return language;
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
